# Configuration docker-compose
version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:9000" 
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: db_ilmu_padi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2wsx1qaz      
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"  
volumes:
  db-volume:
    external: true